version: '3.6'
services:
  db:
    image: mariadb:latest
    hostname: db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile